---
title: "Assignment 9"
author: "Jaclyn Narleski"
date: "2025-03-18"
output: pdf_document
---

# Setup

```{r}

library(tidyverse)
library(here)
library(naniar)
library(DHARMa)
library(gtsummary)
library(broom)

lizards <- read.csv("jrn_lizard.csv")
lizard_npp <- read.csv("jrn_lizard_npp.csv")

```

# Logistic Regression

Do snout-to-vent length, sex, and vegetation zone at time of capture significantly predict if a lizard tail is recorded as whole?

## Data Tidying

```{r}

lizards <- lizards %>%
  filter(spp == "UTST")

```

## Examine Data

```{r}

(hist1 <- ggplot(data = lizards, aes(x = SV_length)) +
    geom_histogram() +
    theme_bw())

(hist2 <- ggplot(data = lizards, aes(x = sex)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

(hist3 <- ggplot(data = lizards, aes(x = zone)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

(hist4 <- ggplot(data = lizards, aes(x = tail)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

(hist5 <- ggplot(data = lizards, aes(x = SV_length,
                                            fill = tail)) +
    geom_histogram(na.rm = TRUE) +
    theme_bw())

(hist6 <- ggplot(data = lizards, aes(x = sex,
                                            fill = tail)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

(hist7 <- ggplot(data = lizards, aes(x = zone,
                                            fill = tail)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

```

## Fit Regression Model

```{r}

lizards$sex <- factor(lizards$sex, 
                      levels = c("F", "J", "M", "NA"))

lizards$zone <- factor(lizards$zone,
                       levels = c("C", "G", "M", "T"))

lizards$tail <- factor(lizards$tail,
                       levels = c("B", "W", "NA"))

tail_mod <- glm(tail ~ SV_length + zone + sex, 
                data = lizards,
                family = "binomial")

summary(tail_mod)

simulateResiduals(tail_mod) %>% plot()

```

```{r}

svlength_vector <- rep(seq(from = 0, to = 50), 4)

sex_vector <- c(rep("F", 51),
                 rep("M", 51),
                 rep("J", 51),
                 rep("NA", 51))

zone_vector <- c(rep("C", 51),
                 rep("G", 51),
                 rep("M", 51),
                 rep("T", 51))

data_pred <- data.frame(svlength_vector, sex_vector, zone_vector)
colnames(data_pred) <- c("SV_length", "sex", "zone")

prediction <- predict(tail_mod,
                      newdata = data_pred,
                      type = "response",
                      se.fit = TRUE)

data_fig <- data.frame(data_pred,
                       prediction$fit,
                       prediction$se.fit)

colnames(data_fig) <- c("SV_length", 
                        "Sex", "Zone", "probability", "se")

ggplot(data_fig, aes(x = SV_length,
                     y = probability)) +
  geom_line(aes(color = Zone)) +
  geom_ribbon(aes(ymin = probability - se,
                  ymax = probability + se,
                  fill = Zone), alpha = 0.3) +
  labs(x = "Temperature (degrees C)",
       y = "Probability of Hypoxia",
       color = "Season",
       fill = "Season") +
  theme_bw()
```

# Poisson Regression

Do season and plant species percent cover significantly predict lizard counts?

```{r}

(hist8 <- ggplot(data = lizard_npp, aes(x = season)) +
    geom_histogram(stat = "count", na.rm = TRUE) +
    theme_bw())

(hist9 <- ggplot(data = lizard_npp, aes(x = BOER)) +
    geom_histogram(na.rm = TRUE) +
    theme_bw())

(hist10 <- ggplot(data = lizard_npp, aes(x = LATR)) +
    geom_histogram(na.rm = TRUE) +
    theme_bw())

(hist11 <- ggplot(data = lizard_npp, aes(x = PRGL)) +
    geom_histogram(na.rm = TRUE) +
    theme_bw())

(hist12 <- ggplot(data = lizard_npp, aes(x = SCBR)) +
    geom_histogram(na.rm = TRUE) +
    theme_bw())

(hist13 <- ggplot(data = lizard_npp, aes = lizard_count)) +
  geom_histogram(na.rm = TRUE)

```

## Fit Regression Model

```{r}

lizard_npp$season <- factor(lizard_npp$season, 
                      levels = c("F", "W", "S"))

lizard_nppmod <- glm(lizard_count ~ season + BOER + LATR + PRGL + SCBR,
                data = lizard_npp,
                family = "poisson")

summary(lizard_nppmod)
plot(lizard_nppmod)

# Remove more outlier rows
lizard_npp2 <- lizard_npp[-c(32, 47, 50, 1),]

lizard_nppmod2 <- glm(lizard_count ~ season + BOER + LATR + PRGL + SCBR,
                data = lizard_npp2,
                family = "poisson")

summary(lizard_nppmod2)
plot(lizard_nppmod2)

lizard_nppmod3 <- glm(lizard_count ~ season + PRGL + SCBR,
                data = lizard_npp2,
                family = "poisson")

summary(lizard_nppmod3)
plot(lizard_nppmod3)

lizard_nppmod4 <- glm(lizard_count ~ season + BOER + PRGL + SCBR,
                data = lizard_npp2,
                family = "poisson")

summary(lizard_nppmod4)
plot(lizard_nppmod4)

tbl_regression(lizard_nppmod4)


```

